# Generated by Django 4.0 on 2021-12-30 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0004_site_last_verified'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('num_servers', models.PositiveIntegerField(default=1)),
                ('num_requests', models.PositiveIntegerField(default=1, help_text='Number of requests per server')),
                ('started_on', models.DateTimeField(blank=True, null=True)),
                ('scheduled_on', models.DateTimeField(blank=True, null=True)),
                ('completed_on', models.DateTimeField(auto_now_add=True)),
                ('min_time', models.PositiveIntegerField(blank=True, null=True)),
                ('max_time', models.PositiveIntegerField(blank=True, null=True)),
                ('mean_time', models.PositiveIntegerField(blank=True, null=True)),
                ('completed_requests', models.PositiveIntegerField(blank=True, null=True)),
                ('failed_requests', models.PositiveIntegerField(blank=True, null=True)),
                ('sys_error_requests', models.PositiveIntegerField(blank=True, help_text='The number of requests that failed due to a system error.', null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
        ),
    ]
